services:
  web:
    image: ghcr.io/phistoh/einker:latest
    pull_policy: always
    command: gunicorn -w 1 -b 0.0.0.0:8000 einker.web:app
    restart: unless-stopped
    ports:
      - "8269:8000"
    volumes:
      - ./data:/app/data:Z
      - ./incoming:/app/incoming:Z
    environment:
      - APP_BASE_DIR=/app
      - HOME=/tmp
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  watcher:
    image: ghcr.io/phistoh/einker:latest
    command: python -m einker.watcher
    restart: unless-stopped
    volumes:
      - ./data:/app/data:Z
      - ./incoming:/app/incoming:Z
    environment:
      - APP_BASE_DIR=/app
      - HOME=/tmp
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
